# filepath: .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

              # Replace the placeholder with the secret token
            - name: Replace token placeholder
              run: |
                  sed -i "s/{{APPLE_MAPKITJS_TOKEN}}/${APPLE_MAPKITJS_TOKEN}/g" index.html
              env:
                  APPLE_MAPKITJS_TOKEN: ${{ secrets.APPLE_MAPKITJS_TOKEN }}
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: . # Adjust if your files are in a subdirectory
